### ISSUE TITLE
Notebook took too long to render (viewing on GitHub)

### ISSUE THREAD

**Issue by sgbaird** [arpanbiswas52/PaperNotebooks#1]
![image](https://user-images.githubusercontent.com/45469701/178062558-31d1eb3e-6caa-40a2-9db7-41e642637f72.png)

**Comment by sgbaird** [comment]
Maybe you could add the Colab links on the README with a short description for each notebook + the REF(s)?

**Comment by arpanbiswas52** [comment]
Thanks for pointing out.

I have added detail description for all the individual papers with notebook links.
For the large files, please download and open in Colab as those respective files have been updated in my colab.

Please feel free to ask any further questions. Thank you
